/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package executargramatica;

import modelo.Identificador;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Paulo Eduardo Martins
 */
public class Tabela extends javax.swing.JFrame {

    /**
     * Creates new form Tabela
     * @param ids
     */
    public Tabela(List<Identificador> ids)
    {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DefaultTableModel tm = new DefaultTableModel();
        tm.addColumn("nome");
        tm.addColumn("tipo");
        tm.addColumn("inicializada");
        tm.addColumn("usada");
        tm.addColumn("escopo");
        tm.addColumn("parametro");
        tm.addColumn("posicaoParametro");
        tm.addColumn("dimensões");
        tm.addColumn("função");
        for (Identificador id : ids)
        {
            Vector vector = new Vector();
            vector.add(id.getNome());
            vector.add(id.getTipo());
            vector.add(id.isInicializada());
            vector.add(id.isUsada());
            vector.add(id.getEscopo());
            vector.add(id.isParametro());
            vector.add(id.getPosicaoParametro());
            vector.add(id.getDimensoes());
            vector.add(id.isFuncao());
            tm.addRow(vector);
        }
        jTable1.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
